### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by BabakFarshchian** [snezhig/obsidian-front-matter-title#220]
I love this plugin because all my file names are automatically generated. Without this plugin I cannot use Obsidian!

I have though one issue. The plugin starts always normally but often stops working after a while when in use, and Obsidian reverts to showing file names in file browser etc. I have not managed to regenerate the situation but I suspect it is in vaults that have more than 2-300 files, and it happens quite often (but not always) when I do a search.

**Comment by snezhig** [comment]
Hi, can you please open console in the application `ctrl+shift+i` и look for any errors there?

**Comment by BabakFarshchian** [comment]
> Hi, can you please open console in the application `ctrl+shift+i` и look for any errors there?

Hi. Sorry for late reply. The thing is that I have not managed to recreate the issue I reported here. I wonder if the latest update to Obsidian did something to fix it? I will continue to observe and will update this issue.

**Comment by BabakFarshchian** [comment]
This bug shows up again. I have the latest version of the plugin.

I am not able to reproduce it. I suspect it happens when I do search, or when I have many notes. But I am not sure. It seems like it happens less frequently after the latest update to Obsidian. I used ctrl-shift-i but cannot see any errors there.

**Comment by BabakFarshchian** [comment]
Update: I found some info about the error (need to learn how to use the console!)

app.js:1 Obsidian Developer Console
plugin:dataview:20327 Dataview: version 0.5.67 (requires obsidian 0.13.11)
plugin:obsidian-release-timeline:8385 loading obsidian-release-timeline
plugin:obsidian-outliner:3221 Loading obsidian-outliner
VM202 plugin:obsidian-front-matter-title-plugin:11496 Migrate from 3.8.1 to 3.8.3 by v3_8_3
VM202 plugin:obsidian-front-matter-title-plugin:11496 Migrate from 3.8.1 to 3.9.0 by v3_9_0
app.js:1 Received URL action Object
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'collapsed')
    at e.updateWorkspace (app.js:1:2355911)
    at l (app.js:1:522936)
    at c (app.js:1:523052)
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'collapsed')
    at e.updateWorkspace (app.js:1:2355911)
    at e._onLayoutChange (app.js:1:2355372)
    at l (app.js:1:522936)
    at c (app.js:1:523052)
plugin:dataview:12894 Dataview: all 545 files have been indexed in 0.191s (545 cached, 0 skipped).
plugin:obsidian-release-timeline:7658 20231127071005
plugin:obsidian-release-timeline:7659 table date, title
from "journal"
sort desc
moment.min.js:2 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2023-11-03:21:54, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (app://obsidian.md/lib/moment.min.js:2:3257)
    at Ea (app://obsidian.md/lib/moment.min.js:2:21634)
    at Fa (app://obsidian.md/lib/moment.min.js:2:22211)
    at S (app://obsidian.md/lib/moment.min.js:2:22294)
    at M (app://obsidian.md/lib/moment.min.js:2:207)
    at eval (plugin:obsidian-release-timeline:8031:73)
    at Array.filter (<anonymous>)
    at WeekTimeline.eval (plugin:obsidian-release-timeline:8031:31)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-release-timeline:69:24)
X @ moment.min.js:2
plugin:obsidian-release-timeline:7658 20231127071005
plugin:obsidian-release-timeline:7659 table date, title
from "journal"
sort desc
plugin:obsidian-front-matter-title-plugin:11496 Migrate from 3.8.1 to 3.8.3 by v3_8_3
plugin:obsidian-front-matter-title-plugin:11496 Migrate from 3.8.1 to 3.9.0 by v3_9_0

**Comment by BabakFarshchian** [comment]
OK I have also discovered that at least this bug always shows up when I click on the home button that the plugin Homepage creates in the left-side menu. So it is not so random anymore :-) The problem is that when it happens I cannot see any error messages in the console.

https://github.com/mirnovov/obsidian-homepage

**Comment by snezhig** [comment]
Front Matter Title is being maintained again and a new version is out. The old issue/PR backlog has been reviewed against current Obsidian (1.12.7) and is being closed; all open PRs are closed too. The reports and ideas are kept in the maintenance plan.

If this still affects you on the latest version, or you have a feature request, please open a new issue with a short description (and repro steps + versions for bugs). Thanks!
